# -------------------------------------------------------------------------------------
# Azure DevOps Pipeline for on-boarding WSO2 Micro Integrator base Docker Image
# --------------------------------------------------------------------------------------

parameters:
  # WSO2 Micro Integrator Updates 2.0 update level
  - name: WSO2_MI_UPDATE_LEVEL
    displayName: Updates 2.0 update level for WSO2 Micro Integrator
    type: string

variables:
  - template: ./common-variables.yaml
  # Base Micro Integrator version
  - name: MI_BASE_VERSION
    value: '4.0.0'

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: ./onboard-image-template.yaml
    parameters:

      WSO2_IMAGE_REG_SERVICE_CONNECTION: $(WSO2_IMAGE_REG_SERVICE_CONNECTION)
      ACR_SERVICE_CONNECTION: $(ACR_SERVICE_CONNECTION)
      ACR_REG_IDENTIFIER: $(ACR_REG_IDENTIFIER)
      WSO2_PRODUCT_NAME: 'Micro Integrator'
      SOURCE_CONTAINER_IMAGE_REPOSITORY: 'wso2mi'
      TARGET_CONTAINER_IMAGE_REPOSITORY: 'wso2mi-neo'
      CONTAINER_IMAGE_TAG: $(MI_BASE_VERSION).${{ parameters.WSO2_MI_UPDATE_LEVEL }}
