# -------------------------------------------------------------------------------------
# Azure DevOps Pipeline for on-boarding WSO2 API Manager base Docker Image
# --------------------------------------------------------------------------------------

parameters:
  # WSO2 API Manager Updates 2.0 update level
  - name: WSO2_APIM_UPDATE_LEVEL
    displayName: Updates 2.0 update level for WSO2 API Manager
    type: string

variables:
  - template: ./common-variables.yaml
  # Base API Manager version
  - name: APIM_BASE_VERSION
    value: '4.0.0'

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: ./onboard-image-template.yaml
    parameters:

      WSO2_IMAGE_REG_SERVICE_CONNECTION: $(WSO2_IMAGE_REG_SERVICE_CONNECTION)
      ACR_SERVICE_CONNECTION: $(ACR_SERVICE_CONNECTION)
      ACR_REG_IDENTIFIER: $(ACR_REG_IDENTIFIER)
      WSO2_PRODUCT_NAME: 'API Manager'
      SOURCE_CONTAINER_IMAGE_REPOSITORY: 'wso2am'
      TARGET_CONTAINER_IMAGE_REPOSITORY: 'wso2am'
      CONTAINER_IMAGE_TAG: $(APIM_BASE_VERSION).${{ parameters.WSO2_APIM_UPDATE_LEVEL }}
