# -------------------------------------------------------------------------------------
# Azure DevOps Pipeline for deploying a WSO2 API Manager Product Helm Chart
# --------------------------------------------------------------------------------------

parameters:
  - name: AM_UPDATE_LEVEL
    type: string
    default: '51'
    displayName: 'WSO2 Update level of WSO2 API Manager to be used'

trigger:
  - none

variables:
  - template: ./common-variables.yaml
  - group: WSO2_SUB_CONFIGURATIONS

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: product-helm-chart-source
      type: github
      name: chirangaalwis/apim-is-km-deployment-resources
      ref: refs/heads/enable-secure-vault
      endpoint: chirangaalwis

jobs:
  - template: ./deploy-product-chart.yaml
    parameters:
      KUBERNETES_SERVICE_CONNECTION: $(KUBERNETES_SERVICE_CONNECTION)
      KUBERNETES_NAMESPACE_FOR_PRODUCT_WORKLOADS: $(KUBERNETES_NAMESPACE_FOR_PRODUCT_DEPLOYMENT)
      HELM_CHART_ROOT: 'deployment/am-pattern-3'
      HELM_RELEASE_NAME: 'apim'
      AZURE_KEY_VAULT_SERVICE_CONNECTION: $(AZURE_KEY_VAULT_SERVICE_CONNECTION)
      DEPLOYMENT_AZURE_KEY_VAULT_NAME: $(DEPLOYMENT_AZURE_KEY_VAULT_NAME)
      HELM_INPUT_VALUES: |
        wso2.subscription.username="chiranga@wso2.com"
        wso2.subscription.password=$(WSO2_SUBSCRIPTION_PASSWORD)
        wso2.deployment.am.dockerRegistry="wso2srernd.azurecr.io"
        wso2.deployment.am.imageName=wso2am
        wso2.deployment.am.imageTag="4.0.0.${{ parameters.AM_UPDATE_LEVEL }}"
        wso2.deployment.am.customConfig.cryptography.keyStores.primary.password=$(AM-PRIMARY-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.keyStores.secondary.password=$(AM-SECONDARY-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.keyStores.internal.password=$(AM-INTERNAL-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.trustStorePassword=$(AM-CERT-TRUST-STORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.keyStores.primary.password=$(MI-PRIMARY-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.keyStores.secondary.password=$(MI-SECONDARY-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.keyStores.internal.password=$(MI-INTERNAL-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.trustStorePassword=$(MI-CERT-TRUST-STORE-PASSWORD)
