# -------------------------------------------------------------------------------------
# Azure DevOps Pipeline for deploying a WSO2 API Manager Product Helm Chart
# --------------------------------------------------------------------------------------

trigger:
  - none

variables:
  - template: ./common-variables.yaml

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: ./deploy-product-chart.yaml
    parameters:
      KUBERNETES_SERVICE_CONNECTION: $(KUBERNETES_SERVICE_CONNECTION)
      KUBERNETES_NAMESPACE_FOR_PRODUCT_WORKLOADS: $(KUBERNETES_NAMESPACE_FOR_PRODUCT_DEPLOYMENT)
      HELM_CHART_ROOT: 'deployment/am-pattern-3'
      HELM_RELEASE_NAME: 'apim'
      AZURE_KEY_VAULT_SERVICE_CONNECTION: $(AZURE_KEY_VAULT_SERVICE_CONNECTION)
      DEPLOYMENT_AZURE_KEY_VAULT_NAME: $(DEPLOYMENT_AZURE_KEY_VAULT_NAME)
      HELM_INPUT_VALUES: |
        wso2.deployment.am.dockerRegistry="wso2srernd.azurecr.io"
        wso2.deployment.am.imageName=wso2am-neo
        wso2.deployment.am.imageTag=4.0.0.52
        wso2.deployment.am.customConfig.cryptography.keyStores.primary.password=$(AM-PRIMARY-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.keyStores.secondary.password=$(AM-SECONDARY-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.keyStores.internal.password=$(AM-INTERNAL-KEYSTORE-PASSWORD)
        wso2.deployment.am.customConfig.cryptography.trustStorePassword=$(AM-CERT-TRUST-STORE-PASSWORD)
        wso2.deployment.mi.dockerRegistry="wso2srernd.azurecr.io"
        wso2.deployment.mi.imageName=wso2mi-neo
        wso2.deployment.mi.imageTag=4.0.0.27
        wso2.deployment.mi.customConfig.cryptography.keyStores.primary.password=$(MI-PRIMARY-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.keyStores.secondary.password=$(MI-SECONDARY-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.keyStores.internal.password=$(MI-INTERNAL-KEYSTORE-PASSWORD)
        wso2.deployment.mi.customConfig.cryptography.trustStorePassword=$(MI-CERT-TRUST-STORE-PASSWORD)
